const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Cnds.IsImmovable,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Behaviors.Physics.Exps.Mass
	];
};
self.C3_JsPropNameTable = [
	{locked: 0},
	{Physics: 0},
	{Tween: 0},
	{Anchor: 0},
	{physprop: 0},
	{ground: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{cursor: 0},
	{cursoreffect: 0},
	{selector: 0},
	{Sprite: 0},
	{Text: 0},
	{ScrollTo: 0},
	{camera: 0},
	{spawntype: 0},
	{spawntypeuid: 0},
	{animations: 0},
	{pickedentity: 0},
	{paused: 0}
];

self.InstanceType = {
	physprop: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	cursor: class extends self.ISpriteInstance {},
	cursoreffect: class extends self.ISpriteInstance {},
	selector: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	camera: class extends self.ISpriteInstance {}
}